// This file is generated by `npm run generate:station-sdk`.
// Do not edit manually.

import createClient from "openapi-fetch";
import type { components, paths } from "./generated/station-openapi";

const baseUrl = process.env.NEXT_PUBLIC_STATION_API_BASE_URL ?? "http://localhost:3212";
const client = createClient<paths>({ baseUrl });

type ApiErrorEnvelope = {
  error?: {
    code?: string;
    message?: string;
    detail?: components["schemas"]["ApiErrorDetailPayloadDto"];
  };
};

function extractApiErrorMessage(error: unknown) {
  if (!error || typeof error !== "object") {
    return null;
  }

  const envelope = error as ApiErrorEnvelope;
  return typeof envelope.error?.message === "string" ? envelope.error.message : null;
}

function extractApiErrorCode(error: unknown) {
  if (!error || typeof error !== "object") {
    return null;
  }

  const envelope = error as ApiErrorEnvelope;
  return typeof envelope.error?.code === "string" ? envelope.error.code : null;
}

function extractApiErrorDetail(error: unknown) {
  if (!error || typeof error !== "object") {
    return null;
  }

  const envelope = error as ApiErrorEnvelope;
  return envelope.error?.detail ?? null;
}

export class ApiError extends Error {
  status: number;
  code: string | null;
  detail: components["schemas"]["ApiErrorDetailPayloadDto"] | null;

  constructor(
    status: number,
    message?: string | null,
    code?: string | null,
    detail?: components["schemas"]["ApiErrorDetailPayloadDto"] | null
  ) {
    super(message ?? `API request failed: ${status}`);
    this.name = "ApiError";
    this.status = status;
    this.code = code ?? null;
    this.detail = detail ?? null;
  }
}

async function expectData<T>(request: Promise<{ data?: T; error?: unknown; response: Response }>): Promise<T> {
  const { data, error, response } = await request;

  if (data !== undefined) {
    return data;
  }

  const message = extractApiErrorMessage(error);
  const code = extractApiErrorCode(error);
  const detail = extractApiErrorDetail(error);

  throw new ApiError(response.status, message, code, detail);
}

async function expectDataOrAllowedError<T>(
  request: Promise<{ data?: T; error?: T | unknown; response: Response }>,
  allowedStatuses: number[]
): Promise<T> {
  const { data, error, response } = await request;

  if (data !== undefined) {
    return data;
  }

  if (allowedStatuses.includes(response.status) && error !== undefined) {
    return error as T;
  }

  const message = extractApiErrorMessage(error);
  const code = extractApiErrorCode(error);
  const detail = extractApiErrorDetail(error);

  throw new ApiError(response.status, message, code, detail);
}

export type ApiErrorCode = components["schemas"]["ApiErrorCode"];
export type ApiErrorIssue = components["schemas"]["ApiErrorIssueDto"];
export type ApiErrorDetailPayload = components["schemas"]["ApiErrorDetailPayloadDto"];
export type ApiErrorDetail = components["schemas"]["ApiErrorDetailDto"];
export type ApiErrorResponse = components["schemas"]["ApiErrorResponseDto"];
export type HealthResponse = components["schemas"]["HealthResponseDto"];
export type ReadinessResponse = components["schemas"]["ReadinessResponseDto"];
export type StationSummary = components["schemas"]["StationSummaryDto"];
export type StationSearchResponse = components["schemas"]["StationSearchResponseDto"];
export type NearbyStationsResponse = components["schemas"]["NearbyStationsResponseDto"];
export type LineCatalogEntry = components["schemas"]["LineCatalogItemDto"];
export type LineCatalogResponse = components["schemas"]["LineCatalogResponseDto"];
export type LineStationsResponse = components["schemas"]["LineStationsResponseDto"];
export type OperatorStationsResponse = components["schemas"]["OperatorStationsResponseDto"];
export type DatasetSnapshotRef = components["schemas"]["DatasetSnapshotRefDto"];
export type DatasetStatusResponse = components["schemas"]["DatasetStatusResponseDto"];
export type DatasetSnapshotChangeCounts = components["schemas"]["DatasetSnapshotChangeCountsDto"];
export type DatasetSnapshot = components["schemas"]["DatasetSnapshotDto"];
export type DatasetSnapshotsResponse = components["schemas"]["DatasetSnapshotsResponseDto"];
export type DatasetChangeKind = components["schemas"]["DatasetChangeKindDto"];
export type DatasetChangeVersionRef = components["schemas"]["DatasetChangeVersionRefDto"];
export type DatasetChangeDetail = components["schemas"]["DatasetChangeDetailDto"];
export type DatasetChangeEvent = components["schemas"]["DatasetChangeEventDto"];
export type DatasetChangesResponse = components["schemas"]["DatasetChangesResponseDto"];

export async function getHealth() {
  return expectData(client.GET("/health"));
}

export async function getReadiness() {
  return expectDataOrAllowedError(client.GET("/ready"), [503]);
}

export async function getDatasetStatus() {
  return expectData(client.GET("/v1/dataset/status"));
}

export async function listDatasetSnapshots(limit = 20) {
  return expectData(
    client.GET("/v1/dataset/snapshots", {
      params: {
        query: { limit }
      }
    })
  );
}

export async function listDatasetChanges(limit = 20, snapshotId?: number | null) {
  return expectData(
    client.GET("/v1/dataset/changes", {
      params: {
        query: {
          limit,
          snapshot_id: snapshotId ?? undefined
        }
      }
    })
  );
}

export async function searchStations(q: string, limit = 10) {
  return expectData(
    client.GET("/v1/stations/search", {
      params: {
        query: { q, limit }
      }
    })
  );
}

export async function searchNearbyStations(lat: number, lng: number, limit = 10) {
  return expectData(
    client.GET("/v1/stations/nearby", {
      params: {
        query: { lat, lng, limit }
      }
    })
  );
}

export async function listLineCatalog(q = "", limit = 60) {
  return expectData(
    client.GET("/v1/lines/catalog", {
      params: {
        query: { q, limit }
      }
    })
  );
}

export async function listLineStations(lineName: string, operatorName?: string | null) {
  return expectData(
    client.GET("/v1/lines/{line_name}/stations", {
      params: {
        path: { line_name: lineName },
        query: {
          operator_name: operatorName ?? undefined
        }
      }
    })
  );
}

export async function listOperatorStations(operatorName: string) {
  return expectData(
    client.GET("/v1/operators/{operator_name}/stations", {
      params: {
        path: { operator_name: operatorName }
      }
    })
  );
}
