name: terraform-fmt

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: terraform fmt
        run: tofu fmt -check -recursive infra/terraform
